### ISSUE TITLE
Batch containers : better doc, and a way to "parsetemplate"

### ISSUE THREAD

**Issue by 31416r** [UCL-INGI/INGInious#130]
The doc on batch containers is really awful, incomplete and, in my opinion, completely useless. This should be improve in order to allow people to grasp what is really possible with this wonderful feature (ex. with a real example that run sherlock).

Maybe we should provide some super easy way to run some pre-defined commands on courses (like sherlock, but maybe other things as well), along with the possibility to give some parameter along the way, without going through the painful process of building the container and configuring it. Should this be some kind of plugin ?

Also, and this is maybe another issue but I'm not sure afterreading the doc, it should be possible to "parsetemplate" from inside a batch container. I think of a case where the submissions only contain partial code entered by students: in order to run new treatments (ex. more tests, or plagiarism detection), it is often necessary to insert the student code into the template of the original question. Maybe it is already possible, but people are complaining about it.

**Comment by GuillaumeDerval** [comment]
My opinion is that batch containers were a bad idea, because they do not solve the initial problem.

Originally, batch containers were created to be able to run JPlag (sherlock) on a course. 

We then created them to be able to take all the submissions of a given course, put them in a given container with a well-defined structure on the disk, and let the container make its work.

However, it soon became apparent that it was not solving the problem for JPlag, for multiple reasons:
- The main idea of INGInious is that courses are individual and completely separated object. JPlag needs input from other years (courses) to work properly, so it is completely orthogonal to the way INGInious is made
- JPlag takes way too much configuration options, via command line. The first idea was to propose a simple interface extrapolated from labels in the container. It proved ineffective and more cumbersome than running the command by hand on the user own computer to debug the calls to JPlag.
- We then implemented a way to statically store config options in the task, via on-disk files. I think it is a way too complicated way to configure JPlag...
- We have a very nice tool to download submissions (which is a bit slow, but strictly less than batch containers) that fullfill all the needs to be able to do exactly what batch containers does locally.

IMHO, it is far more simple for everyone to run JPlag by hand on the teacher's computer for now.

A better idea would be to simply drop JPlag from the batch container, or at least from the visible batch container, and to create a full-fledged plugin for it. It is probably the way to go with batch containers: maybe they should only be an API for the plugins?

Having a standard batch container that inits everything and takes a (set of) scripts as input would be cool too.

**Comment by GuillaumeDerval** [comment]
The current goal for more or less everything in the webapp is to have anything particular in plugins, and everything global in the core, so it particularly make sense, IMO

**Comment by 31416r** [comment]
I agree that dedicated plugins may be the way to go with batch containers (I even suggeted it in my first post). I also like the idea of batch containers as API accessible only from plugins.

But this emphases even more the need for a good documentation on batch container *and* on plugins.
