### ISSUE TITLE
Unifying LTI / webapp view of users

### ISSUE THREAD

**Issue by dirkcgrunwald** [UCL-INGI/INGInious#146]
I would like to have users who only access the system through the LTI interface have their userid added to the course and then have their scores visible in the webapp interface.

In our scenario, students may use the LTI to submit their data, but the teachers / admins could use the webapp interface to e.g. download all submissions or run bulk grading options.

This means that for us, course enrollment would be set up by Moodle and we wouldn't have to add them to Inginious as well.

Is there a reason this doesn't already work? Is it as simple as adding the users to the course in mongo?

**Comment by dirkcgrunwald** [comment]
I'd be happy to explore other ways to resolve this feature request.

The specific need to integrate the Web and LTI frontends have to do with allowing the instructor to perform batch operations, such as running the JPLAG checker or downloading all of the assignments.

Some options for solutions include:
1) Could add all LTI submissions into a 'group' defined by the LTI context information (i.e. same launching point from the LTI consumer). This would disambiguate the web and LTI uses.

2) Could provide "LTI web interface" when the instructor visits the LTI link using the LTI provided role information. That interface could provide the batch operations.

I don't like solution #2 because, in practice, an instructor is going to be aware of the web interface when designing tasks.

I'd like to find some design that could be implemented in the next 20-40 days so that we could deploy INGInious at our university.

**Comment by anthonygego** [comment]
I'm not sure to get the point for your first solution. Could you be more specific ?

For now, I think the patch you comitted could do the trick. Everything depends on your webapp usage. As long as you don't configure a task for grouped submission on the LTI, there will be no problem. And if this would happen, it won't crash: you'll just probably see weird results in the submissions as the LTI will allow a unique student to submit to a task the webapp would disallow if the task is configured as grouped task.

This really depends on your usage: you can, for instance, tell the students to submit on Moodle, use your patch to make them register automatically, set the courses not accessible to the students on the webapp and use it for administration only. This setup should work fine. 

In this case, by working a little bit your patch and moving the functions modifying data in the the DB into the common files, I think it is possible to make it less sensitive to the possible changes we would make until finding a better solution.

We'll probably separate the batch containers and studio from the webapp in the near future. A download feature is available for the LTI, it is not as complete, but we'll try to make it better. Common statistics would however require more work, but we are currently investigating new architecture for the frontends.

**Comment by dirkcgrunwald** [comment]
This scenario:

> This really depends on your usage: you can, for instance, tell the students to submit on Moodle,   use your patch to make them register automatically, set the courses not accessible to the students on the webapp and use it for administration only. This setup should work fine.

is exactly the one I was looking for.

My suggested change (1) was based on my understanding of the LTI protocol and my understanding that felt it might be useful to have LTI users be distinct from groups created through the web interface. LTI defines both roles (e.g. student, instructor) and "content points" which are often the name of the course -- the website http://ltiapps.net/test/tc.php lets you set these as an TLI consumer (and /tp.php as a provider).

In our usage, we would be using a single "course" or task set within INGInious for each course. Different instances of the course (years, terms) would require new task sets. Thus, having students enrolled in a specific course/task set isn't a problem.

If we used the LTI context information to group students by LTI context, multiple Moodle courses could connect to the same INGInious course/task-set and their students would be in different groups. That is a more flexible mechanism and would be compatible with the "one-Moodle-one-INGInious" model described above.

Btw, in terms of consolidating different systems and thinking about alternatives, I wonder if you have seen the mod_vpl package (http://vpl.dis.ulpgc.es/). This is an interesting system that has a more substantive Moodle integration (including VNC based display for X applications) for multiple source files and testing. It uses an external code execution environment (similar to the CodeRunner system - http://coderunner.org.nz/ ). I keep thinking that there are lots of these containment / evaluation systems (also -- the INGInious one is one of the most secure and interesting, but the delay (5-6 seconds for evaluation) may not make it work for the applications that CodeRunner is designed for (quizzes). There is also the http://www.autolabproject.com/ component called "tango" which is a generalized code execution containment system.

**Comment by anthonygego** [comment]
OK, I understand. I think it would be quite a though work thinking that we're about to change the frontends architecture, in order to make more coherent products, in which this problem would be solved.

Thank you for feedback comparing INGInious to other solutions you've found. This is really useful for us as we're currently in a stage thinking about architectural changes and we'd like to make more users adopt the tool.

- We didn't know about VPL. The initial goal of the INGInious development was not to provide virtual classrooms with free access to the software, but only grading features.
Providing such a feature in INGInious could be done without much work I think, by reusing the current SSH debug feature. Typically, this would consist in allowing the student to access an SSH session without the grading script so they can access to the exact same set of software as the one used for grading, and set X redirection if needed. We did not explore this possibility yet. I think this would require a more particular attention to hardware resources.
- CodeRunner seem particularly poor in terms of functionalities to us (by looking at the screenshots): this expected/got approach does not provide as much flexibility as we currently do and gives the possibility to the student to cheat by making his program return the appropriate set of input/output.  However, as you say, for quizz, this could do the job.
- It is clear Autolab is a very similar solution to ours as it relies on Docker and enables making tests with every set of software. However, we're slowly going to another direction concerning the user interfaces.

The choice we've made for INGInious up until now are the results of several years of tries and errors and Docker seemed to be the only solution for such genericity. We are however aware of the container launch/stop time which may be quite prohibitive for small assignments. By tweaking the daemon configuration, some speedup can be gained: using devicemapper is for example not recommended by Docker.  We already planed to investigate this issue and try to came with a solution in the next months.

We're trying to remain as generic as possible, in order to meet a maximum of requirements. Since our migration to Python3 and the development of a new backend, you are even now able to write a grader which does not rely on Docker. MCQ grading methods were separated that way.

**Comment by anthonygego** [comment]
LTI and webapp frontends are have been merged into one unique frontend. We've chosen to let students from the host LMS bind their contextual information to their INGInious account, which is now an actual piece of data stored in database. So they need to login once in INGInious webapp to be able to submit from the LTI interface.

Courses can now be set as webapp or LTI courses (this to avoid users submitting for their LTI course and scores not giving back to the host LMS). In the later case, students only see the course via the host LMS but administrators have the exact same set of features as for a webapp course, that is, statistics, task editor,...

All this stuff is not documented yet and more things are still do be done. Meanwhile we've dropped the batch operations system because it was not easily maintenable and not easy to use for users (the procedure was found too complex). That means we've temporarily dropped the JPlag support. However, we'll try to get it back as a plugin feature soon, which would better integrates with INGInious.
