### ISSUE TITLE
Add list of schools/universities, that use INGInious

### ISSUE THREAD

**Issue by bogem** [UCL-INGI/INGInious#191]
I think, it will be cool and inspiring to have a list of organisations (educational institutes) in README, that use INGInious.
What do you think about it?

**Comment by GuillaumeDerval** [comment]
Done on the website :-)

**Comment by bogem** [comment]
At Hochschule Schmalkalden we tried to integrate INGInious, but unfortunately it's complicated for our needs and we decided to looking for another alternative.

**Comment by anthonygego** [comment]
It would be really nice if you can provide us with more feedback about what you wish you could do with INGInious.

**Comment by bogem** [comment]
@anthonygego The main problem is writing bash scripts for launching and checking the solutions. Professors should write a lot of boilerplate bash code for basic operations. We tried to find a simpler solution, but found nothing. 
I wrote a system that we want ([https://github.com/bogem/palp](https://github.com/bogem/palp)), but I can't support and develop it alone.

**Comment by anthonygego** [comment]
Thank you for this feedback. This is actually a problem we've been trying to tackle for some time and some ideas were already discussed.

First, INGInious was historically designed for that purpose, and is the result of a quite long experience in our department. This may seem crazy according to your feedback, but the main reason is the same as for you : human resources, and time. We were asked for a solution that will not simply match answers and that will support any technology without additional dev. The best way to match everybody's need in time was to let them do as many things as possible. Some people just want to run a simple program and check that the output is correct with a set of inputs. Others want to do unit tests with their own framework, to recover from segfault in C for instance. Others want conditional grading according to some set of options. Others want to do some pre-processing (linter,...). Others want to produce an animated simulation of a game AI.

However, there is, indeed, a bigger step to get started with INGInious than with a simpler CS grading platform that would compile a file and then simply check with some input files if the produced output files are correct. Currently, we've observed than the grading process is almost the same for all the exercises of a course, mainly because it uses the same technologies and was written by the same teaching assistant. The later actually wrote one grading script some day and then rely on it as an additional framework in top of INGInious basic APIs. Such examples are available in our UCL-INGI/CS1-Java and UCL-INGI/SINF1252 repos. This is currently the most efficient way to design exercises.

Again the main reason why we work like this is the lack of resources. We cannot simply design a simpler solution for everyone, even though that would be great. INGInious is currently developed at the CS department which main activity is research: we just can't simply ask for more development resources. 

Actually we designed INGInious with some ways to tackle this problem in mind:
1. Not the most convenient but the most flexible, the most observed method: maintaining some templates/framework per course. We taught the tasks writers to re-use their scripts as much as possible. We recently pushed a way to share common files in a course in order to reduce the amount of copy/paste.
1. Designing new Docker-based environments that will automate the job. This is the first method we had in mind, but it suprisingly never was popular. Less flexible, the idea is to rely on Docker layering and build new containers with a built-in run script. This way you can design a task with only a set of input files, a set of output files, and your built-in run script will do the check automatically.
1. Designing new /extending existing agents. This is similar to the previous point, but without relying on Docker. It may be interesting for some simpler problems that do not need to write code that will be run.

Our best wish would be to see the community build on top of INGInious in a similar way to keep a generic core code base easy to maintain while providing powerful free pluggable frameworks to ease the exercises writing, because we do not have time to support and maintain code for everything.
