### ISSUE TITLE
What are the system requirements for INGInious?

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#286]
I would like to rent a cloud-computer for installing INGInious.  How much disk-space, memory and CPU power do I need at the minimum to run it?

**Comment by anthonygego** [comment]
This really depends on what you want to do with it and the experience you want to provide to your users. 

For the backend, the system requirements for running a task are not higher than what is required on your own machine. So if you want to assess a typical Java program, you only need to meet the Java system requirements in terms on CPU and RAM. Concerning the disk space, you'll have to provide enough space for Docker containers, which are additionnal layers added to a minimal CentOS install.

Then you'll probably want to multiply those requirements by the maximum number of jobs (execution slots) you want to be performed simultaneously. This is the most important factor. I strongly recommend SSDs to speed up Docker (usually provided by default nowadays in the cloud). INGInious Docker agent allocates by default one CPU core by execution slot. Then, the maximum amount of RAM per slot is the total RAM of the machine divided by the number of slots. Empirically, you can then size your backend machine by allocating  _mean execution time of jobs * mean jobs debit per second_ CPU cores and _CPU cores * maximum expected RAM for a job_ of RAM

For instance, if you expect to have a mean load of 3 jobs/seconds requiring a mean execution time of 2 sec and a maximum amount of 2GB RAM, a 6-cores machine with 12GB RAM will ensure that the waiting jobs queue will be empty in average and that they are running in good conditions.

For the frontend, I strongly recommend to put it on another machine if it's possible. Your users will probably want a more responsive frontend than assessment process. So if the backend machine undergoes an heavy load due to a peak, assessment will take a bit longer but the browser experience will still be pleasant. You'll have to provide enough disk space and RAM for the MongoDB database.
