### ISSUE TITLE
Students code needs to be isolated from code used for grading.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#32]
This issue has already been raised offline. This bug is to track the progress and schedule the task at some milestone.

**Comment by GuillaumeDerval** [comment]
The best thing to do would be to run two containers, as Pythia 0 did.

I have this scheme in mind:
* INGInious-backend launches a first container, for example ```ingi/inginious-c-java7```
* The container runs the ```run``` script, located at ```/task/run```
* This script creates the files needed to launch the student script, in a specified directory, for example ```/student```
* And then use a new command, for example ```run_student```, that
    * Launches a new container, possibly different from the current container image (for example, ```ingi/inginious-c-mozart2```)
    * This container launches the command specified, in the directory ```/student```, only directory shared between the two containers
    * Wait for completion, while checking the timeout and memory using cgroups (that will fix the problem we have currently with timeouts and forks)
    * (stdin/stdout usage will still be possible)
* The main container then checks the results of the student's code (received from stdout and in the directory ```/student```) and set an appropriate feedback

Drawbacks:
* launching (and deleting after it is done) a container can take some time (approx. 0.5 sec)
* breaks compatibility with current tasks (may be preserved with a compatibility layer)

Advantages:
* The student's code is not run in a container that can interact with INGInious
* The student's code is isolated from the grading
* The handling of the timeout is not done in the container that runs the code of the student's
* The handling of the timeout will be more accurate, and will take into account forks
* It will be possible to use different containers for grading and running students code (using Mozart to check Python3 output is a must have :trollface:)
* Launching multiple different containers, with each time different timeouts, will be possible
* ...

And we can link this with #33 I think.

I will try to do that before the meeting of the 22...

**Comment by layus** [comment]
Nice summary :-)

Some comments about the drawbacks.
 - Note that starting two containers is still O(1) :trollface: 
 - I think we could manage to add the functionality without breaking compatibility, but it may not be desirable.
 - Huh ? Maybe too technical for me :-D

And one idle thought about the advantages.
 - While using mozart2 to parse python3 output is not a killer feature _per se_, it is really good to have a different container for grading. For example, tar and unzip are not present `inginious-c-mozart2` and I had to write some python code to simulate them... So a bash/python grading container would be a relief.

And finally, why did you drop your previous idea of using unix user/file permissions ?

**Comment by GuillaumeDerval** [comment]
> Note that starting two containers is still O(1) :trollface:

I will repeat it to myself everytime I think about the performances of this.

> G.D: we will need to secure the container used for grading as it will have direct access to docker...

> Huh ? Maybe too technical for me :-D

Giving access to Docker mainly consist in giving the root access on the host machine, due to some Docker features (like privileged containers). I will probably play with sudo and things like that inside the "grading container" to ensures a maximum security. 

But I'm less concerned about what task makers write than about what the students write :wink:

> While using mozart2 to parse python3 output is not a killer feature per se, it is really good to have a different container for grading. For example, tar and unzip are not present inginious-c-mozart2 and I had to write some python code to simulate them... So a bash/python grading container would be a relief. For example, https://gist.github.com/layus/64d9d2a0d6c051b86974 is what I had to do to uncompress the archive within the (grading) container.

Wow. You should have asked for an update of ```inginious-c-mozart2```. These commands should be available in every container, at least for debugging of tasks.

> And finally, why did you drop your previous idea of using unix user/file permissions ?

I began the implementation of this weeks ago, but I found it not very elegant. Using ```chown```/```chmod``` everywhere could be really painful when doing tasks; moreover, I've been trying for a very long time to fix the problem with processes that fork, breaking the way we handle timeouts.

Creating new containers allows us to use the cgroups cpu accounting, that counts all the cpu time used by all the processes of a container. We could have used it outside the main container, but that would have broken the usage of external docker instances (we would have to use SSH to access cgroups..., etc.).

So having a main grading container, in which we mount ```/sys/fs/cgroup``` from the host and the Docker socket, solves all theses problems, and allows to develop additional features (such as subtasks with different timeout/memory values).

**Comment by GuillaumeDerval** [comment]
https://gist.github.com/GuillaumeDerval/32284a5933a8e203212c is an even better solution, I think.
This is a variation of what I proposed above.

I will try to implement (an early version of) that in the next days, and will run speed tests :-)

**Comment by GuillaumeDerval** [comment]
Fixed by #36
