### ISSUE TITLE
Support custom Dockerfiles

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#35]
It would be nice to have support for custom Dockerfiles. For example, a Dockerfile in the root of the course would define a 'custom' container accessible for all the tasks.

This would avoid asking for an update of the containers when we want to add an executable.

If building container images from Dockerfiles is secure enough, this would be a great usability jump :-)

**Comment by GuillaumeDerval** [comment]
(mainly notes for myself)

This is not secure for now, as Docker does not support user namespaces. In fact, for now, giving root access in a container is virtually the same as giving root access to the host machine.

The feature is planned to be implemented in Docker 1.9.0, which is planned for release on October 2015.
(see https://github.com/docker/docker/wiki/Engine-1.9.0)

So we will definitively implement this, but later.

**Comment by GuillaumeDerval** [comment]
INGInious is made to be student-proof, teacher-proof, but it is difficult to make it container-creator-proof.

The containers are always run using the root account in INGInious; it is only safe because we know that the script called inside the container (`/usr/bin/INGInious`) will automatically switch to the user `worker` after doing some particular task.

With custom containers, this contract can be broken; giving root access in the container to anyone else than INGInious itself is too dangerous for now.

I'm going to close this issue. However, maybe we should think about alternatives. 

(What about using nix to allow to design custom containers? The idea would be to have a local nix store and allow tasks to define which packages they want. Maybe later :D)
