### ISSUE TITLE
Configuration.yml should support environment variables

### ISSUE THREAD

**Issue by larranaga** [UCL-INGI/INGInious#350]
This is kind of a blind issue, I couldn't find anywhere in your documentation an instance where environment variables were used inside the `configuration.yml` file. This would be helpful to hide sensitive information (such as api keys, secrets, and database configurations).

**Comment by GuillaumeDerval** [comment]
It is not currently possible, and I agree it would be useful, notably when using cloud providers (that tend to send everything to machines with env variables).

This is sadly not an issue we will resolve soon. Feel free to contribute, it is probably a small amount of coding :-)

On a side note, I'm not that convinced that using env vars instead of config files directly is more secure: the env variables of any process are accessible via a fake file in /proc as long as you are the user who started the process. If your configuration.yaml have the correct access rights, it is equivalent.

**Comment by GuillaumeDerval** [comment]
Actually, maybe the best thing to do is to create a small script that parses the env variables and put them inside the configuration.yaml when the application starts. Nothing too complicated and could avoid to add again more code in this part of the code that needs a good refactor.

**Comment by larranaga** [comment]
That sounds like a really good solution, thanks a lot!
