### ISSUE TITLE
Accessing LTI information when using LTI frontend

### ISSUE THREAD

**Issue by dirkcgrunwald** [UCL-INGI/INGInious#693]
We are using LTI to automatically enter grades in an LMS (canvas and moodle).

Students enter the URL of their git repo. Then, within the INGInious grading container, we checkout that git repo using a personal access token (PAT) and run the grading scripts.

Because we are using a PAT, we can checkout any repo within our (github classroom) organization. I added a "ownership check to make certain the student submits only their own repo. I wrote support checking code to make certain that **input.get_username()** maps to a Git user name that has permission to the provided repo.

However, it's not clear that **input.get_username()** maps to the user identity from our LMS. I had been assuming that this was what was being done by the "LTI binding" step, but we see some students with odd bindings (e.g. "uniqueusername" is one such glitch from a "Results" page of existing assignments).

Is it possible to access LTI information within a grading container? What should the **input.get_username()** return?

**Comment by dirkcgrunwald** [comment]
In particular, I think what would be useful is if the information from `user_manager:session_lti_info` (e.g. the LTI provided email, username, realname & roles) be provided in the `/.__input/__inputdata.json` file with a prefix of LTI or as another JSON dictionary (e.g. 'LTI' : { 'email' : ....} etc )

Or, possibly better yet, just pass all the LTI launch data ( e.g. https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide#toc-13 ) without the logic of e.g. trying to determine the full name of the LTI user.

I've found when using Github Classroom that different LMS's map different information to the LTI launch data. While it's theoretically possible to remap some of these, it's administratively difficult. For example, sometimes we can use 'userid' as a unique key for student info and other times 'username' or 'lis_person_contact_email_primary'.

**Comment by anthonygego** [comment]
Currently ``input.get_username()`` returns the INGInious account username. 

There is no technical difficulty to add the LTI information into the submission metadata. The only thing I fear is that it's currently possible, in a course with without the "send back scores" option set, to submit through LTI or through the webapp, leading to different results if the run script relies on this piece of information. @GuillaumeDerval, @Drumor What are your thoughts about this ?

We could also just sent the user bidings in the submission metadata but that will probably lead to a privacy issue as this would send personal information that are not useful for grading.

**Comment by Drumor** [comment]
First option seems good to me. The send back scores "issue" must be effectively investigate.

**Comment by dirkcgrunwald** [comment]
In our own application, we weren't thinking of using the callback information -- we use the **feedback.set_grade** method for that.

The primary thing that we need (and I think would be needed by others) is the identity information. The presence or absence of this could be used to customize the scripts -- in our case, we only want students to access through LTI.

**Comment by anthonygego** [comment]
It's OK then. If you could make that contribution that would be great. I think it should just be a matter of one or two additional lines here : https://github.com/UCL-INGI/INGInious/blob/bca4d59cb249476977da951f8faa4729db5dc1e3/inginious/frontend/submission_manager.py#L270 since the LTI info are accessible through ``user_manager.session_lti_info()``
https://github.com/UCL-INGI/INGInious/blob/bca4d59cb249476977da951f8faa4729db5dc1e3/inginious/frontend/user_manager.py#L141
If I'm not mistaken, the ``email``, ``realname``and ``username`` fields of the dictionary are those from the LTI platform.

It would be nice to filter those information though, as the consumer key and outcome* fields may constitute a security issue if exposed. I'm also not sure if the code at the container side is ready for a dictionary in the user inputs. You may want to pass a list, or separate fields.

**Comment by jyounggo** [comment]
PR #699  is submitted for this issue.
