### ISSUE TITLE
RST directive "hidden-until" doesn't seem to work 

### ISSUE THREAD

**Issue by Manon-Oreins** [UCL-INGI/INGInious#856]
RST directive "hidden-until" doesn't seem to work and acts like the "hidden" rst directive. Whatever the date is after the "hidden-until" directive the content will be hidden.

**Comment by anthonygego** [comment]
Can you tell in which part you're trying to using it and what are the steps to reproduce ?

This should work

        Not hidden

        .. hidden-until:: 2022-08-01
          
            hidden until 1st August

        Not hidden
        
and display

> A part of this feedback is hidden until 01/08/2022 00:00:00. Please come back later and reload the submission to see the full feedback.

It is working in task descriptions with ``master`` and on inginious.org

**Comment by Manon-Oreins** [comment]
Ok I just tested it and it worked but it's not documented well (missing a ':' in the command line and I didn't see it was missing when I tried it). Guess I could change the code I did for the PR if necessary

**Comment by anthonygego** [comment]
This does not achieve the exact same goal, even if it's possible to hide everything using the rst directive, so it does not need to be adapted necessarily.

Actually, now that you've made me think about it, I'm really wondering if we shouldn't even need a more robust mechanism for such a feature. We are currently refactoring some core task concepts in order to make tasks course-agnostic (class-agnostic) and ease their sharing among courses. Hardcoding deadlines (or similar date-related concepts) into the task definition goes against that principle and has already set some difficulties in the past (updating the dates every year, different dates for different audiences, ...).

A more robust way to implement such a feature while easing task sharing could be to deprecate the ``hidden-until`` directive and add a more generic one, with no argument, and store the date into the task settings in the task dispenser, so that this setting could be different for every course based on the same tasks.
